---

- name: Ensure Elasticsearch apt signing key is installed
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Ensure Elasticsearch 0.90.x repository is installed
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/0.90/debian stable main" state=present update_cache=yes

- name: Ensure elasticsearch is installed
  apt: pkg={{item}} state=installed
  with_items:
    - openjdk-7-jre-headless
    - elasticsearch

- name: Ensure elasticsearch config is in place
  copy: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify:
    - restart elasticsearch

- name: Install head (Plugin)
  command: /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head creates=/usr/share/elasticsearch/plugins/head/_site/.gitignore

- name: Install Paramedic (Plugin)
  command: /usr/share/elasticsearch/bin/plugin -install karmi/elasticsearch-paramedic creates=/usr/share/elasticsearch/plugins/paramedic/_site/.gitignore

- name: Install Bigdesk (Plugin)
  command: /usr/share/elasticsearch/bin/plugin -install lukas-vlcek/bigdesk creates=/usr/share/elasticsearch/plugins/bigdesk/_site/.gitignore

- name: Install Inquisitor (Plugin)
  command: /usr/share/elasticsearch/bin/plugin -install polyfractal/elasticsearch-inquisitor creates=/usr/share/elasticsearch/plugins/inquisitor/.gitignore
